<?= "<?php\n" ?>

// generated by `make:user:msgphp`
// this configuration may be merged into your existing application configuration

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use function Symfony\Component\DependencyInjection\Loader\Configurator\ref;

return function (ContainerConfigurator $container) {
<?php if ($config): ?>
    $container->extension('msgphp_user', <?= $config ?>);

<?php endif; ?>
<?php if($services): ?>
    $container->services()
        ->defaults()
            ->private()
            ->autoconfigure()
            ->autowire()

<?php foreach ($services as $service): ?>
        <?= str_replace("\n", "\n        ", $service)."\n" ?>
<?php endforeach; ?>
    ;
<?php endif; ?>
};
