<?php

declare(strict_types=1);

/*
 * This file is part of the MsgPHP package.
 *
 * (c) Roland Franssen <franssen.roland@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$extensionConfig = $servicesConfig = $sep = '';

if ($config) {
    $extensionConfig = <<<PHP
    \$container->extension('msgphp_user', ${config});
PHP;
}

foreach ($services as $service) {
    $servicesConfig .= $sep.'        '.str_replace("\n", "\n        ", $service);
    $sep = "\n\n";
}

if ($servicesConfig) {
    if ($extensionConfig) {
        $extensionConfig .= "\n\n";
    }
    $servicesConfig = <<<PHP
    \$container->services()
        ->defaults()
            ->private()
            ->autoconfigure()
            ->autowire()

${servicesConfig}
    ;
PHP;
}

return <<<PHP
<?php

// generated by `make:user:msgphp`
// this configuration may be merged into your existing application configuration

use Symfony\\Component\\DependencyInjection\\Loader\\Configurator\\ContainerConfigurator;
use function Symfony\\Component\\DependencyInjection\\Loader\\Configurator\\ref;

return function (ContainerConfigurator \$container) {
${extensionConfig}${servicesConfig}
};

PHP;
